name: CI
on:

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services: 
      postgres:
        image: postgres
        ports: 
          - 5432/tcp
      redis:
        image: redis
        ports: ['6379:6379']
        options: --entrypoint redis-server 
    steps:
      - uses: actions/checkout@v3
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1.110.0
        with:
          ruby-version: 3.1.1
          bundler-cache: true

      - uses: Borales/actions-yarn@v3.0.0
        with:
          cmd: install

      - name: Install Dependencies
        env:
          DATABASE_URL: postgres://postgres:@localhost:5432/test
          REDIS_URL: redis://@localhost:6379/0
          RAILS_ENV: test
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        run: |
          sudo apt-get install -yqq libpq-dev
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rails db:prepare --trace
          bundle exec rails test


